freebsd_instance:
  image_family: freebsd-12-1

task:
  name: FreeBSD 12.1
  cargo_cache:
    folder: $CARGO_HOME/registry
    fingerprint_script: cat Cargo.lock || echo ""
  setup_script:
    - pkg install -y pkgconf fusefs-libs
    - fetch https://sh.rustup.rs -o rustup.sh
    - sh rustup.sh -y
  build_script:
    - . $HOME/.cargo/env
    - cargo build --all --all-targets
  doc_script:
    - . $HOME/.cargo/env
    - cargo doc --all --no-deps --all-features
  test_script:
    - . $HOME/.cargo/env
    - cargo test --all --all-targets
  before_cache_script: rm -rf $CARGO_HOME/registry/index


task:
  name: Mac OS X Monterey
  macos_instance:
    image: ghcr.io/cirruslabs/macos-monterey-base:latest
  cargo_cache:
    folder: $CARGO_HOME/registry
    fingerprint_script: cat Cargo.lock || echo ""
  setup_script:
    - brew install gcc curl
    - brew install --cask macfuse
    - curl https://sh.rustup.rs -o rustup.sh
    - sh rustup.sh -y
  build_script:
    - . $HOME/.cargo/env
    - cargo build --all --all-targets
  doc_script:
    - . $HOME/.cargo/env
    - cargo doc --all --no-deps --all-features
  test_script:
    - . $HOME/.cargo/env
    - cargo test --all --all-targets
  before_cache_script: rm -rf $CARGO_HOME/registry/index
